[project]
name = "automail"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.2.10",
    "langchain-openai>=1.1.9",
    "langgraph-cli[inmem]>=0.4.12",
    "openai>=2.20.0",
]
